config/routes.rb
Rails.application.routes.draw do

  mount LetterOpenerWeb::Engine, at: "/letter_opener"

  devise_for :admins, :controllers => { :invitations => 'admins/invitations' }
  devise_for :users

  root 'pages#home'

  get 'pages/contact'
  get 'pages/about'
  get 'pages/home'

  resources :users

  namespace :backend do
    resources :dashboards
    resources :admins
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base

  include Reuseable


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
    :recoverable, :rememberable, :trackable, :validatable



  validates :first_name, presence: true
  validates :last_name, presence: true 
  validates :phone, presence: true
  validates :phone, numericality: { only_integer: true }
  validates :address_line1, presence: true
  validates :address_line2, presence: true
  validates :code, presence: true
  validates :town, presence: true
  validates :email, presence: true



  def self.clear_expired
    Admin.invitation_not_accepted.map { |c| c.destroy unless c.valid_invitation? }
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
    
end

app/controllers/admins/invitations_controller.rb
class Admins::InvitationsController < Devise::InvitationsController
  def create
    self.resource = invite_resource
    resource_invited = resource.errors.empty?

    yield resource if block_given?

    if resource_invited
      if is_flashing_format? && self.resource.invitation_sent_at
        set_flash_message :notice, :send_instructions, :email => self.resource.email
      end
      if self.method(:after_invite_path_for).arity == 1
        respond_with resource, :location => after_invite_path_for(current_inviter)
      else
        respond_with resource, :location => after_invite_path_for(current_inviter, resource)
      end
    else
      respond_with_navigational(resource) { redirect_to backend_admins_url }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_premitted_parameters, if: :devise_controller?
  layout :layout_by_resource

  def after_sign_in_path_for(resource)
    if current_user
      user_path(current_user)
    elsif current_admin
      backend_dashboards_path
    end
  end

  protected
  def configure_premitted_parameters
    if resource_name == :user
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, 
                                                         :last_name, 
                                                         :email, 
                                                         :password, 
                                                         :remeber_me])

      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, 
                                                                :last_name])
    elsif resource_name == :admin
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, 
                                                         :last_name, 
                                                         :email, 
                                                         :password, 
                                                         :remeber_me, 
                                                         :address_line1,
                                                         :address_line2,
                                                         :phone,
                                                         :code,
                                                         :town])

      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name,
                                                                :last_name,
                                                                :last_name, 
                                                                :email, 
                                                                :password, 
                                                                :remeber_me, 
                                                                :address_line1,
                                                                :address_line2,
                                                                :phone,
                                                                :code,
                                                                :town])
      devise_parameter_sanitizer.permit(:accept_invitation, keys: [:first_name,
                                                                   :last_name,
                                                                   :last_name, 
                                                                   :email, 
                                                                   :password, 
                                                                   :remeber_me, 
                                                                   :address_line1,
                                                                   :address_line2,
                                                                   :phone,
                                                                   :code,
                                                                   :town])
    end
  end

  private

  def layout_by_resource
    if devise_controller? && resource_name == :admin
      "backend_login_layout"
    else
      "frontend_layout"
    end
  end

  def after_invite_path_for(resource)
    backend_admins_path
  end
end

app/controllers/backend/admins_controller.rb
class Backend::AdminsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_admins

  layout 'backend_layout'
  
  def index
    @admins = Admin.all
  end

  private

  def set_admins
    Admin.clear_expired
  end

end

app/controllers/backend/dashboards_controller.rb
class Backend::DashboardsController < ApplicationController
  before_action :authenticate_admin!
  layout 'backend_layout'

  def index
    @welcome_msg = "Welcome to backend"
  end
end

app/controllers/backends_controller.rb
class BackendsController < ApplicationController
  before_action :authenticate_admin!
  layout 'backend_layout'

  def dashboard 
    @welcome_msg = "Welcome to backend"
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def contact
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  layout 'customer_profile_layout'
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
  def admin_status(admin)
    if admin.owner || admin.confirmed?
      material_icon.done.css_class('text-success')
    else
      'Oczekuje'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backend/dashboards_helper.rb
module Backend::DashboardsHelper
end

app/helpers/backends_helper.rb
module BackendsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/backend/admins/index.html.erb
<div class="col-md-12">
  <h2>Administratorzy</h2>
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="row">
        <div class="col-md-12">
          <%= simple_form_for(Admin.new, url: admin_invitation_path, html: {class: 'form-inline' }) do |f| %> 
            <%= f.input :email, required: true, error: 'Email is mandatory', placeholder: 'Email', label: false %> 
            <%= f.button :submit, 'Wyślij zaproszenie', class: 'btn btn-default' %> 
          <% end %> 
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-12">
          <table class="table table-striped">
            <thead>
              <tr>
                <td>Imię i Nazwisko</td>
                <td>Email</td>
                <td>Status</td>
              </tr>
            </thead>
            <tbody>
              <% @admins.each do |admin| %> 
                <tr>
                  <td> <%= admin.fullname  %> </td>
                  <td> <%= admin.email %> </td>
                  <td> <%= admin_status(admin) %> </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/backend/dashboards/index.html.erb
<div class='well'>
  <h1>Admin Dashboard</h1>
  <h2> Msg from controller: <%= @welcome_msg %> </h2>
</div>

app/views/backends/dashboard.html.erb
<div class='well'>
  <h1>Admin Dashboard</h1>
  <h2> Msg from controller: <%= @welcome_msg %> </h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodtrackV10</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>


    <%= render "partials/main_nav" %>
    <div class="container">
      <%= render "partials/flash_messages" %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/backend_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodtrackV10</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render 'partials/backend_nav' %> 
    <div class="container">
      <div class="row">
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li><%= link_to "Administratorzy", backend_admins_path  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div>
        <div class="col-lg-9">
          <div class="well">backend-layout</div>
          <%= render "partials/flash_messages" %>
          <%= yield %>
        </div>
      </div><!--/row-->

  </body>
</html>

app/views/layouts/backend_login_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodtrackV10</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render 'partials/backend_nav' %> 
    <div class="container">
      <div class="row">
        <div class="well">backend-login-layout</div>
        <%= render "partials/flash_messages" %>
        <%= yield %>
      </div>
  </body>
</html>

app/views/layouts/customer_profile_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodtrackV10</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>


    <%= render "partials/main_nav" %>
    <div class="container">
      <div class="well">customer-profile-layout</div>
      <%= render "partials/flash_messages" %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/frontend_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodtrackV10</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>


    <%= render "partials/main_nav" %>
    <div class="container">
      <div class="well">frontend-layout</div>
      <%= render "partials/flash_messages" %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/about.html.erb
<div class="well">
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>
  <%= icon 'flag' %> 
  <%= material_icon.face %>
</div>

app/views/pages/contact.html.erb
<div class="well">
  <h1>Pages#contact</h1>
  <p>Find me in app/views/pages/contact.html.erb</p>
  <%= icon 'flag' %> 
  <%= material_icon.face %>
</div>

app/views/pages/home.html.erb
<div class="well">
  <h1>Pages#home</h1>
  <p>Find me in app/views/pages/home.html.erb</p>
  <%= icon 'flag' %> 
  <%= material_icon.face %>
</div>

app/views/partials/_backend_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Foodtrack", backend_dashboards_path, class: 'navbar-brand' %> 
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if admin_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_admin.first_name %>
              <%= current_admin.last_name %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_admin_registration_path %></li>
              <li><%= link_to 'Log out', destroy_admin_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_flash_messages.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <p class="notice"> <%= notice %> </p>
  </div>
<% elsif alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <p class="alert"> <%= alert %> </p>
  </div>
<% end %> 

app/views/partials/_main_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Foodtrack", root_path, class: 'navbar-brand' %> 
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to 'Home', root_path %> </li>
        <li> <%= link_to 'About', pages_about_path %> </li>
        <li> <%= link_to 'Contact', pages_contact_path %> </li>
        <% if user_signed_in? %>  
          <li> <%= link_to "My Profile", user_path(current_user) %> </li>
          <li> <%= link_to "Log out", destroy_user_session_path, method: :delete %> </li>
        <% elsif %>
          <li> <%= link_to 'Sign in', new_user_session_path  %> </li>
          <li> <%= link_to 'Sign up', new_user_registration_path  %> </li>
        <% end %> 
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/show.html.erb
<div class='well'>
  <h1>Customer Profile Page</h1>
  <h2> Welcome <%= @user.first_name %> <%= @user.last_name %> </h2>
</div>